# Generated by Django 6.0.3 on 2026-03-08 04:32

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(default=booking.models.generate_ticket_id, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('location', models.TextField(help_text='Location coordinates or address')),
                ('hours', models.IntegerField(default=2)),
                ('rent_date', models.DateField()),
                ('rent_time', models.TimeField()),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='selfies/')),
                ('selfie_verified', models.BooleanField(default=False)),
                ('total_amount', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(default=0)),
                ('balance_amount', models.IntegerField(default=0)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_signature', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('damage_policy_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sky Bicycle Rental', max_length=100)),
                ('contact_phone', models.CharField(default='+919876543210', max_length=15)),
                ('contact_email', models.EmailField(default='ride@skybicycle.in', max_length=254)),
                ('address', models.TextField(default='Downtown Hub')),
                ('bikes_available', models.IntegerField(default=6)),
                ('rate_per_hour', models.IntegerField(default=200)),
                ('booking_amount', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
